apiVersion: v1
kind: Service
metadata:
  name: ironic-prometheus-exporter
  namespace: openstack
  labels:
    app: ironic-prometheus-exporter
spec:
  type: ClusterIP
  selector:
    app: ironic-prometheus-exporter
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
