# This rule is not used by the project nautobotop itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sync.rax.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nautobotop
    app.kubernetes.io/managed-by: kustomize
  name: nautobot-admin-role
rules:
- apiGroups:
  - sync.rax.io
  resources:
  - nautobots
  verbs:
  - '*'
- apiGroups:
  - sync.rax.io
  resources:
  - nautobots/status
  verbs:
  - get
