# This rule is not used by the project nautobotop itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sync.rax.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nautobotop
    app.kubernetes.io/managed-by: kustomize
  name: nautobot-viewer-role
rules:
- apiGroups:
  - sync.rax.io
  resources:
  - nautobots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.rax.io
  resources:
  - nautobots/status
  verbs:
  - get
