---
version: "3.8"
name: understack-nautobot
services:
  redis:
    image: "redis:7-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD"
    env_file:
      - "default-creds.env"
      - "development.env"
