[files]
extend-exclude = [
    ".venv",
    "venv",
    "assets",
    "schema/argo-workflows.json",
    "python/understack-workflows/tests/json_samples/",
    "containers/*/patches",
    "go.mod",
    "ansible/roles/statuses/defaults/main.yaml",
    "apps/infra/*.yaml",
    "apps/operators/*.yaml",
    "apps/global/*.yaml",
    "apps/site/*.yaml",
    "apps/openstack/*.yaml",
]

[default]
extend-ignore-identifiers-re = [
    "ironic_retrive_*",
]
extend-ignore-re = [
    "chartVersion:.*",
]

[default.extend-words]
# Don't correct "HPE"
HPE = "HPE"
fo = "fo"
sme = "sme"
4caf50 = "4caf50"
ist = "ist"
# upstream OpenStack Helm typo
retreive = "retreive"
# Intentionally truncated process names in health probe (15 char limit)
metadat = "metadat"
