apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-understack-project.yaml
  - mariadb.yaml
  - rabbitmq-cluster.yaml
  - memcached.yaml
  - postgres-db.yaml
  - nautobot.yaml
  - keystone.yaml
  - argo-workflows.yaml
  - argo-events.yaml
  - ironic.yaml
  - dexidp.yaml
