apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-openstack-resource-controller.yaml
  - https://github.com/k-orc/openstack-resource-controller/releases/download/v2.4.0/install.yaml
