apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../apps/appsets/project-understack-infra.yaml
- ../../../../../apps/appsets/project-understack-operators.yaml
- ../../../../../apps/appsets/project-understack.yaml
- appset-of-understack.yaml
