---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ironic-mariadb-db.yaml
  - ironic-rabbitmq-queue.yaml
  - dnsmasq-pvc.yaml
  - dnsmasq-ss.yaml
  - ironic-ks-user-baremetal.yaml
  # less than ideal addition but necessary so that we can have the ironic.conf.d loading
  # working due to the way the chart hardcodes the config-file parameter which then
  # takes precedence over the directory
  - configmap-ironic-bin.yaml
  - ./runbook-crd
  - ./runbook-operator
  # Graphical consoles
  - role-ironic-graphical-console.yaml
  - role-binding-ironic-graphical-console.yaml
