dex:
  # disable shipping ArgoCD's dex, we'll use the Undercloud provided one
  enabled: false
notifications:
  # disable notifying users or GitHub
  enabled: false
applicationSet:
  # enable the ApplicationSet controller to auto-generate Applications
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
server:
  ingress:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone
  rbac:
    policy.csv: |
      # role:ucadmin can sync applications
      p, role:ucadmin, applications, sync, */*, allow
      p, role:ucadmin, applications, update, */*, allow
      # role:ucadmin can update clusters so that they can set branch info
      p, role:ucadmin, clusters, update, *, allow
      # role:ucadmin inherits role:readonly
      g, role:ucadmin, role:readonly
      # members of the ucadmin group get role:ucadmin
      g, ucadmin, role:ucadmin
    policy.default: role:readonly
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
