---
name: build-nautobotop-images

on:
  workflow_dispatch:
  push:
    tags:
      - nautobotop-v*
    paths:
      - "go/nautobotop/**"

jobs:
  build-nautobotop:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: 'go/nautobotop/go.sum'

      - name: Install syft
        uses: anchore/sbom-action/download-syft@f8bdd1d8ac5e901a77a92f111440fdb1b593736b # v0.20.6

      - name: Install Cosign
        uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # v3.10.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to ghcr.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/nautobotop-v}" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --skip=validate
          workdir: go/nautobotop
        env:
          CUSTOM_TAG: ${{ steps.extract_tag.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chart:
    runs-on: ubuntu-latest
    needs:
      - build-nautobotop
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Log in to ghcr.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Package and push Helm chart
        working-directory: go/nautobotop
        env:
          PKG_VER: '${{ github.ref_name }}'
        run: |
          PKG_VER=${PKG_VER#nautobotop-v}
          # update Chart.yaml with tag version
          yq -i ".version = \"${PKG_VER}\"" helm/Chart.yaml
          yq -i ".appVersion = \"${PKG_VER}\"" helm/Chart.yaml
          yq helm/Chart.yaml
          # package chart
          helm package -u -d ${{ github.workspace }} helm
          # push chart to ghcr.io
          helm push ${{ github.workspace }}/nautobotop-${PKG_VER}.tgz \
            oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts
