---
name: build-nautobotop-images

on:
  workflow_dispatch:
  push:
    tags:
      - nautobotop-v*
    paths:
      - "go/nautobotop/**"

jobs:
  build-nautobotop:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Login to ghcr.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/nautobotop-v}" >> $GITHUB_OUTPUT

      - name: Build and deploy Naubotobotop image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: go/nautobotop/
          file: go/nautobotop/Dockerfile
          # push for all main branch commits
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/nautobotop:latest,ghcr.io/${{ github.repository }}/nautobotop:${{ steps.extract_tag.outputs.tag }}
          labels: |
            org.opencontainers.image.version=${{ steps.extract_tag.outputs.tag }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=Nautobot-Operator
            org.opencontainers.image.vendor=Rackspace
            org.opencontainers.image.source=https://rackspace.com/
            org.opencontainers.image.authors=Rackspace

  chart:
    runs-on: ubuntu-latest
    needs:
      - build-nautobotop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Package and push Helm chart
        env:
          PKG_VER: '${{ github.ref_name }}'
        run: |
          PKG_VER=${PKG_VER#nautobotop-v}
          # update Chart.yaml with tag version
          yq -i ".version = \"${PKG_VER}\"" charts/Chart.yaml
          # package chart
          helm package -u -d ${{ github.workspace }} charts
          # push chart to ghcr.io
          helm push ${{ github.workspace }}/nautobotop-${PKG_VER}.tgz \
            oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts

