---
name: build-nautobotop-images

on:
  workflow_dispatch:
  push:
    tags:
      - nautobotop-v*
    paths:
      - "go/nautobotop/**"

jobs:
  build-nautobotop:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: 'go/nautobotop/go.sum'

      - name: Install syft
        uses: anchore/sbom-action/download-syft@0b82b0b1a22399a1c542d4d656f70cd903571b5c # v0.21.1

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to ghcr.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/nautobotop-v}" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --skip=validate
          workdir: go/nautobotop
        env:
          GIT_REPO: ${{ github.repository }}
          CUSTOM_TAG: ${{ steps.extract_tag.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chart:
    runs-on: ubuntu-latest
    needs:
      - build-nautobotop
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Log in to ghcr.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Package and push Helm chart
        working-directory: go/nautobotop
        env:
          PKG_VER: '${{ github.ref_name }}'
        run: |
          PKG_VER=${PKG_VER#nautobotop-v}
          # update Chart.yaml with tag version
          yq -i ".version = \"${PKG_VER}\"" helm/Chart.yaml
          yq -i ".appVersion = \"${PKG_VER}\"" helm/Chart.yaml
          yq helm/Chart.yaml
          # package chart
          helm package -u -d ${{ github.workspace }} helm
          # push chart to ghcr.io
          helm push ${{ github.workspace }}/nautobotop-${PKG_VER}.tgz \
            oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts
