name: Go Tests
on:
  push:
    branches:
      - main
    paths:
      - "go/**"
      - .github/workflows/go-test.yaml
  pull_request:
    paths:
      - "go/**"
      - .github/workflows/go-test.yaml
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
    paths:
      - "go/**"
      - .github/workflows/go-test.yaml

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: List Applications
        id: list_dirs
        run: |
          apps=$(ls -d go/* | xargs -n1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "apps=${apps}"
          # TODO: dexop does not pass tests
          #echo "apps=%s" "${app_array}" >> "$GITHUB_OUTPUT"
          echo "apps=[\"understackctl\"]" >> "$GITHUB_OUTPUT"
        shell: bash
    outputs:
      apps: ${{ steps.list_dirs.outputs.apps }}

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        app: ${{ fromJson(needs.setup.outputs.apps) }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go/${{ matrix.app }}/go.mod

      - name: Test ${{ matrix.app }}
        working-directory: go/${{ matrix.app }}
        run: go test -v ./...
